"""
Report generation module for Nexcomply application
Generates PDF reports using FPDF2
"""

from fpdf import FPDF
from datetime import datetime
import os
import pandas as pd


# fpdf2 >= 2.7.8 changed multi_cell's default post-call cursor position from
# "left margin" to "right edge of the cell".  When w=0 (full page width) the
# right edge IS the right margin, so a subsequent multi_cell(0, …) sees zero
# available width and raises FPDFException.  These constants are passed
# explicitly to every multi_cell call to restore the expected behaviour.
_MC_NEW_X = "LMARGIN"
_MC_NEW_Y = "NEXT"


def _sanitize_text(text):
    """
    Sanitize text so it is safe for FPDF's built-in Latin-1 core fonts.

    FPDF2 core fonts (e.g. Arial/Helvetica) only support the Latin-1
    character set (ISO 8859-1, code points 0x00–0xFF).  Passing Unicode
    characters outside that range causes the library to raise
    ``FPDFException: Not enough horizontal space to render a single
    character`` because the glyph cannot be found and the internal width
    metrics become invalid.

    This helper encodes the string to Latin-1 using the ``'replace'`` error
    handler, which substitutes each unencodable character with the Latin-1
    byte ``0x3F`` (``'?'``), then decodes the result back to a ``str`` so
    FPDF receives a clean, Latin-1-compatible string.
    """
    if not isinstance(text, str):
        text = str(text)
    return text.encode('latin-1', errors='replace').decode('latin-1')


class ComplianceReport(FPDF):
    """Custom PDF class for compliance reports"""
    
    def __init__(self):
        super().__init__()
        self.report_title = "Compliance Gap Analysis Report"
        self.company_name = "Nexcomply"
    
    def header(self):
        """Add header to each page"""
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, _sanitize_text(self.report_title), 0, 1, 'C')
        self.ln(5)
    
    def footer(self):
        """Add footer to each page"""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')
    
    def chapter_title(self, title):
        """Add chapter title"""
        self.set_font('Arial', 'B', 14)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 10, _sanitize_text(title), 0, 1, 'L', 1)
        self.ln(4)
    
    def chapter_body(self, body):
        """Add chapter body text"""
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 6, _sanitize_text(body), new_x=_MC_NEW_X, new_y=_MC_NEW_Y)
        self.ln()
    
    def add_key_value(self, key, value):
        """Add key-value pair"""
        self.set_font('Arial', 'B', 11)
        self.cell(60, 8, _sanitize_text(f"{key}:"), 0, 0)
        self.set_font('Arial', '', 11)
        self.cell(0, 8, _sanitize_text(str(value)), 0, 1)


class ReportGenerator:
    """Class to handle report generation"""
    
    def __init__(self, output_folder="Risk Reports"):
        """
        Initialize report generator
        
        Args:
            output_folder: Folder to save reports
        """
        self.output_folder = output_folder
        os.makedirs(output_folder, exist_ok=True)
    
    def generate_pdf_report(self, report_data, filename=None):
        """
        Generate comprehensive PDF compliance report
        
        Args:
            report_data: Dictionary containing report data
            filename: Optional custom filename
            
        Returns:
            str: Path to generated report
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"Compliance_Report_{timestamp}.pdf"
        
        filepath = os.path.join(self.output_folder, filename)
        
        # Create PDF
        pdf = ComplianceReport()
        pdf.report_title = report_data.get('title', 'Compliance Gap Analysis Report')
        
        # Add first page
        pdf.add_page()
        
        # Executive Summary
        pdf.chapter_title("Executive Summary")
        executive_summary = report_data.get('executive_summary', 
            "This report provides a comprehensive analysis of compliance gaps and recommendations.")
        pdf.chapter_body(executive_summary)
        
        # Report Information
        pdf.chapter_title("Report Information")
        pdf.add_key_value("Report Date", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        pdf.add_key_value("Framework", report_data.get('framework', 'N/A'))
        pdf.add_key_value("Generated By", report_data.get('generated_by', 'System'))
        pdf.ln(5)
        
        # Compliance Score
        pdf.chapter_title("Compliance Score Overview")
        compliance_score = report_data.get('compliance_score', 0)
        pdf.add_key_value("Overall Compliance Score", f"{compliance_score:.2f}%")
        pdf.add_key_value("Target Score", f"{report_data.get('target_score', 85)}%")
        
        status = "COMPLIANT" if compliance_score >= 85 else "NON-COMPLIANT"
        pdf.add_key_value("Status", status)
        pdf.ln(5)
        
        # Gap Summary
        pdf.chapter_title("Gap Analysis Summary")
        gap_summary = report_data.get('gap_summary', {})
        pdf.add_key_value("Total Gaps Identified", gap_summary.get('total_gaps', 0))
        pdf.add_key_value("Critical Gaps", gap_summary.get('critical_gaps', 0))
        pdf.add_key_value("High Priority Gaps", gap_summary.get('high_gaps', 0))
        pdf.add_key_value("Medium Priority Gaps", gap_summary.get('medium_gaps', 0))
        pdf.add_key_value("Low Priority Gaps", gap_summary.get('low_gaps', 0))
        pdf.ln(5)
        
        # Detailed Gap Analysis
        pdf.add_page()
        pdf.chapter_title("Detailed Gap Analysis")
        
        gap_details = report_data.get('gap_details', [])
        if gap_details:
            for i, gap in enumerate(gap_details, 1):
                # Support both key conventions:
                # Analysis page produces 'gap_severity' / 'requirement'
                # Legacy / manual data may use 'severity' / 'description'
                severity = gap.get('gap_severity') or gap.get('severity', 'Unknown')
                description = gap.get('requirement') or gap.get('description', 'N/A')

                pdf.set_font('Arial', 'B', 11)
                pdf.cell(0, 8, _sanitize_text(f"Gap #{i}: {severity} Severity"), 0, 1)
                
                pdf.set_font('Arial', '', 10)
                pdf.multi_cell(0, 6, _sanitize_text(f"Similarity Score: {gap.get('similarity_score', 0):.2f}"), new_x=_MC_NEW_X, new_y=_MC_NEW_Y)
                description_text = description if len(description) <= 5000 else description[:5000] + '... [truncated]'
                pdf.multi_cell(0, 6, _sanitize_text(f"Description: {description_text}"), new_x=_MC_NEW_X, new_y=_MC_NEW_Y)
                pdf.ln(3)
        else:
            pdf.chapter_body("No detailed gap information available.")
        
        # Recommendations
        pdf.add_page()
        pdf.chapter_title("Recommendations")
        recommendations = report_data.get('recommendations', 
            "1. Address critical gaps immediately\n"
            "2. Develop action plan for high priority gaps\n"
            "3. Schedule regular compliance reviews\n"
            "4. Implement continuous monitoring")
        pdf.chapter_body(recommendations)
        
        # Action Items
        pdf.chapter_title("Action Items and Timeline")
        action_items = report_data.get('action_items', [])
        if action_items:
            for item in action_items:
                pdf.set_font('Arial', 'B', 10)
                pdf.cell(0, 6, _sanitize_text(f"• {item.get('priority', 'Medium')} Priority"), 0, 1)
                pdf.set_font('Arial', '', 10)
                pdf.multi_cell(0, 5, _sanitize_text(f"  Action: {item.get('action', 'N/A')}"), new_x=_MC_NEW_X, new_y=_MC_NEW_Y)
                pdf.multi_cell(0, 5, _sanitize_text(f"  Timeline: {item.get('timeline', 'TBD')}"), new_x=_MC_NEW_X, new_y=_MC_NEW_Y)
                pdf.ln(2)
        else:
            pdf.chapter_body("No specific action items defined.")
        
        # Next Steps
        pdf.add_page()
        pdf.chapter_title("Next Steps")
        next_steps = report_data.get('next_steps',
            "1. Review this report with stakeholders\n"
            "2. Prioritize remediation efforts\n"
            "3. Assign responsibilities\n"
            "4. Schedule follow-up assessment")
        pdf.chapter_body(next_steps)
        
        # Save PDF
        pdf.output(filepath)
        
        return filepath
    
    def generate_excel_report(self, gap_data, filename=None):
        """
        Generate Excel report with gap analysis
        
        Args:
            gap_data: DataFrame or list of gap analysis results
            filename: Optional custom filename
            
        Returns:
            str: Path to generated report
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"Gap_Analysis_{timestamp}.xlsx"
        
        filepath = os.path.join(self.output_folder, filename)
        
        # Convert to DataFrame if needed
        if isinstance(gap_data, list):
            df = pd.DataFrame(gap_data)
        else:
            df = gap_data
        
        # Save to Excel
        with pd.ExcelWriter(filepath, engine='openpyxl') as writer:
            df.to_excel(writer, sheet_name='Gap Analysis', index=False)
        
        return filepath
    
    def generate_html_report(self, report_data, filename=None):
        """
        Generate HTML report
        
        Args:
            report_data: Dictionary containing report data
            filename: Optional custom filename
            
        Returns:
            str: Path to generated report
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"Compliance_Report_{timestamp}.html"
        
        filepath = os.path.join(self.output_folder, filename)
        
        # Build HTML content
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>{report_data.get('title', 'Compliance Report')}</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; }}
                h1 {{ color: #2c3e50; }}
                h2 {{ color: #34495e; border-bottom: 2px solid #3498db; padding-bottom: 5px; }}
                .metric {{ background-color: #ecf0f1; padding: 15px; margin: 10px 0; border-radius: 5px; }}
                .critical {{ color: #e74c3c; font-weight: bold; }}
                .high {{ color: #e67e22; font-weight: bold; }}
                .medium {{ color: #f39c12; }}
                .low {{ color: #27ae60; }}
                table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
                th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
                th {{ background-color: #3498db; color: white; }}
                tr:nth-child(even) {{ background-color: #f2f2f2; }}
            </style>
        </head>
        <body>
            <h1>{report_data.get('title', 'Compliance Gap Analysis Report')}</h1>
            <p><strong>Report Date:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
            <p><strong>Framework:</strong> {report_data.get('framework', 'N/A')}</p>
            
            <h2>Executive Summary</h2>
            <p>{report_data.get('executive_summary', 'N/A')}</p>
            
            <h2>Compliance Score</h2>
            <div class="metric">
                <h3>Overall Score: {report_data.get('compliance_score', 0):.2f}%</h3>
            </div>
            
            <h2>Gap Summary</h2>
            <div class="metric">
                <p><strong>Total Gaps:</strong> {report_data.get('gap_summary', {}).get('total_gaps', 0)}</p>
                <p class="critical">Critical: {report_data.get('gap_summary', {}).get('critical_gaps', 0)}</p>
                <p class="high">High: {report_data.get('gap_summary', {}).get('high_gaps', 0)}</p>
                <p class="medium">Medium: {report_data.get('gap_summary', {}).get('medium_gaps', 0)}</p>
                <p class="low">Low: {report_data.get('gap_summary', {}).get('low_gaps', 0)}</p>
            </div>
            
            <h2>Recommendations</h2>
            <p>{report_data.get('recommendations', 'N/A')}</p>
            
        </body>
        </html>
        """
        
        # Save HTML
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return filepath
    
    def generate_all_formats(self, report_data):
        """
        Generate report in all formats (PDF, Excel, HTML)
        
        Args:
            report_data: Dictionary containing report data
            
        Returns:
            dict: Dictionary of generated file paths
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        generated_files = {}
        
        # Generate PDF
        try:
            pdf_path = self.generate_pdf_report(report_data, f"Report_{timestamp}.pdf")
            generated_files['pdf'] = pdf_path
        except Exception as e:
            generated_files['pdf_error'] = str(e)
        
        # Generate Excel
        try:
            gap_data = report_data.get('gap_details', [])
            if gap_data:
                excel_path = self.generate_excel_report(gap_data, f"Gap_Analysis_{timestamp}.xlsx")
                generated_files['excel'] = excel_path
        except Exception as e:
            generated_files['excel_error'] = str(e)
        
        # Generate HTML
        try:
            html_path = self.generate_html_report(report_data, f"Report_{timestamp}.html")
            generated_files['html'] = html_path
        except Exception as e:
            generated_files['html_error'] = str(e)
        
        return generated_files


def create_sample_report_data(gap_summary, gap_details, framework_name="ISO 27001"):
    """
    Create sample report data structure
    
    Args:
        gap_summary: Dictionary with gap summary statistics
        gap_details: List of detailed gap information
        framework_name: Name of the compliance framework
        
    Returns:
        dict: Report data structure
    """
    compliance_score = gap_summary.get('compliance_percentage', 0)
    
    report_data = {
        'title': f'{framework_name} Compliance Gap Analysis Report',
        'framework': framework_name,
        'generated_by': 'Nexcomply System',
        'executive_summary': (
            f"This report presents a comprehensive analysis of compliance gaps "
            f"against the {framework_name} framework. "
            f"The current compliance score is {compliance_score:.2f}%. "
            f"A total of {gap_summary.get('total_gaps', 0)} requirements were analyzed, "
            f"with {gap_summary.get('critical_gaps', 0)} critical gaps identified."
        ),
        'compliance_score': compliance_score,
        'target_score': 85,
        'gap_summary': gap_summary,
        'gap_details': gap_details,
        'recommendations': (
            "Based on the gap analysis, the following recommendations are made:\n\n"
            "1. IMMEDIATE: Address all critical gaps within 30 days\n"
            "2. SHORT-TERM: Resolve high priority gaps within 90 days\n"
            "3. MEDIUM-TERM: Address medium priority gaps within 180 days\n"
            "4. ONGOING: Implement continuous monitoring and improvement\n"
            "5. TRAINING: Provide compliance training to relevant staff\n"
            "6. DOCUMENTATION: Update policy documentation to reflect changes"
        ),
        'action_items': [
            {
                'priority': 'Critical',
                'action': 'Implement missing security controls',
                'timeline': '30 days'
            },
            {
                'priority': 'High',
                'action': 'Update policy documentation',
                'timeline': '60 days'
            },
            {
                'priority': 'Medium',
                'action': 'Conduct staff training',
                'timeline': '90 days'
            }
        ],
        'next_steps': (
            "1. Review this report with executive stakeholders\n"
            "2. Assign ownership for each identified gap\n"
            "3. Develop detailed remediation plan\n"
            "4. Schedule follow-up assessment in 90 days\n"
            "5. Implement continuous monitoring process"
        )
    }
    
    return report_data
